package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallSearchHistory;
import org.tiei.mall.db.domain.mallSearchHistoryExample;

public interface mallSearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    long countByExample(mallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    int deleteByExample(mallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    int insert(mallSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    int insertSelective(mallSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    mallSearchHistory selectOneByExample(mallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    mallSearchHistory selectOneByExampleSelective(@Param("example") mallSearchHistoryExample example, @Param("selective") mallSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    List<mallSearchHistory> selectByExampleSelective(@Param("example") mallSearchHistoryExample example, @Param("selective") mallSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    List<mallSearchHistory> selectByExample(mallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    mallSearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    mallSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    mallSearchHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallSearchHistory record, @Param("example") mallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallSearchHistory record, @Param("example") mallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_search_history
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}