package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallAdmin;
import org.tiei.mall.db.domain.mallAdminExample;

public interface mallAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    long countByExample(mallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    int deleteByExample(mallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    int insert(mallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    int insertSelective(mallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    mallAdmin selectOneByExample(mallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    mallAdmin selectOneByExampleSelective(@Param("example") mallAdminExample example, @Param("selective") mallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    List<mallAdmin> selectByExampleSelective(@Param("example") mallAdminExample example, @Param("selective") mallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    List<mallAdmin> selectByExample(mallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    mallAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    mallAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    mallAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallAdmin record, @Param("example") mallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallAdmin record, @Param("example") mallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}