package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallTopic;
import org.tiei.mall.db.domain.mallTopicExample;

public interface mallTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    long countByExample(mallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    int deleteByExample(mallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    int insert(mallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    int insertSelective(mallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    mallTopic selectOneByExample(mallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    mallTopic selectOneByExampleSelective(@Param("example") mallTopicExample example, @Param("selective") mallTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    mallTopic selectOneByExampleWithBLOBs(mallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    List<mallTopic> selectByExampleSelective(@Param("example") mallTopicExample example, @Param("selective") mallTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    List<mallTopic> selectByExampleWithBLOBs(mallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    List<mallTopic> selectByExample(mallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    mallTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    mallTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    mallTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallTopic record, @Param("example") mallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") mallTopic record, @Param("example") mallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallTopic record, @Param("example") mallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(mallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}