package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallAddress;
import org.tiei.mall.db.domain.mallAddressExample;

public interface mallAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    long countByExample(mallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int deleteByExample(mallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int insert(mallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int insertSelective(mallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    mallAddress selectOneByExample(mallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    mallAddress selectOneByExampleSelective(@Param("example") mallAddressExample example, @Param("selective") mallAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    List<mallAddress> selectByExampleSelective(@Param("example") mallAddressExample example, @Param("selective") mallAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    List<mallAddress> selectByExample(mallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    mallAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    mallAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    mallAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallAddress record, @Param("example") mallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallAddress record, @Param("example") mallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_address
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}