package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallKeyword;
import org.tiei.mall.db.domain.mallKeywordExample;

public interface mallKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    long countByExample(mallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    int deleteByExample(mallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    int insert(mallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    int insertSelective(mallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    mallKeyword selectOneByExample(mallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    mallKeyword selectOneByExampleSelective(@Param("example") mallKeywordExample example, @Param("selective") mallKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    List<mallKeyword> selectByExampleSelective(@Param("example") mallKeywordExample example, @Param("selective") mallKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    List<mallKeyword> selectByExample(mallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    mallKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    mallKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    mallKeyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallKeyword record, @Param("example") mallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallKeyword record, @Param("example") mallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}