package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallSystem;
import org.tiei.mall.db.domain.mallSystemExample;

public interface mallSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    long countByExample(mallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    int deleteByExample(mallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    int insert(mallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    int insertSelective(mallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    mallSystem selectOneByExample(mallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    mallSystem selectOneByExampleSelective(@Param("example") mallSystemExample example, @Param("selective") mallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    List<mallSystem> selectByExampleSelective(@Param("example") mallSystemExample example, @Param("selective") mallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    List<mallSystem> selectByExample(mallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    mallSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    mallSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    mallSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallSystem record, @Param("example") mallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallSystem record, @Param("example") mallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}