package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallGrouponRules;
import org.tiei.mall.db.domain.mallGrouponRulesExample;

public interface mallGrouponRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    long countByExample(mallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByExample(mallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    int insert(mallGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    int insertSelective(mallGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    mallGrouponRules selectOneByExample(mallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    mallGrouponRules selectOneByExampleSelective(@Param("example") mallGrouponRulesExample example, @Param("selective") mallGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    List<mallGrouponRules> selectByExampleSelective(@Param("example") mallGrouponRulesExample example, @Param("selective") mallGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    List<mallGrouponRules> selectByExample(mallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    mallGrouponRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    mallGrouponRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    mallGrouponRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallGrouponRules record, @Param("example") mallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallGrouponRules record, @Param("example") mallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}