package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallAd;
import org.tiei.mall.db.domain.mallAdExample;

public interface mallAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    long countByExample(mallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    int deleteByExample(mallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    int insert(mallAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    int insertSelective(mallAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    mallAd selectOneByExample(mallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    mallAd selectOneByExampleSelective(@Param("example") mallAdExample example, @Param("selective") mallAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    List<mallAd> selectByExampleSelective(@Param("example") mallAdExample example, @Param("selective") mallAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    List<mallAd> selectByExample(mallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    mallAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    mallAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    mallAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallAd record, @Param("example") mallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallAd record, @Param("example") mallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}