package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallCart;
import org.tiei.mall.db.domain.mallCartExample;

public interface mallCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    long countByExample(mallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    int deleteByExample(mallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    int insert(mallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    int insertSelective(mallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    mallCart selectOneByExample(mallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    mallCart selectOneByExampleSelective(@Param("example") mallCartExample example, @Param("selective") mallCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    List<mallCart> selectByExampleSelective(@Param("example") mallCartExample example, @Param("selective") mallCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    List<mallCart> selectByExample(mallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    mallCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    mallCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    mallCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallCart record, @Param("example") mallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallCart record, @Param("example") mallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}