package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallGroupon;
import org.tiei.mall.db.domain.mallGrouponExample;

public interface mallGrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    long countByExample(mallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    int deleteByExample(mallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    int insert(mallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    int insertSelective(mallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    mallGroupon selectOneByExample(mallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    mallGroupon selectOneByExampleSelective(@Param("example") mallGrouponExample example, @Param("selective") mallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    List<mallGroupon> selectByExampleSelective(@Param("example") mallGrouponExample example, @Param("selective") mallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    List<mallGroupon> selectByExample(mallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    mallGroupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    mallGroupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    mallGroupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallGroupon record, @Param("example") mallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallGroupon record, @Param("example") mallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}