package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallCoupon;
import org.tiei.mall.db.domain.mallCouponExample;

public interface mallCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    long countByExample(mallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(mallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    int insert(mallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    int insertSelective(mallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    mallCoupon selectOneByExample(mallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    mallCoupon selectOneByExampleSelective(@Param("example") mallCouponExample example, @Param("selective") mallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    List<mallCoupon> selectByExampleSelective(@Param("example") mallCouponExample example, @Param("selective") mallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    List<mallCoupon> selectByExample(mallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    mallCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallCoupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    mallCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    mallCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallCoupon record, @Param("example") mallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallCoupon record, @Param("example") mallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}