package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallComment;
import org.tiei.mall.db.domain.mallCommentExample;

public interface mallCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    long countByExample(mallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    int deleteByExample(mallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    int insert(mallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    int insertSelective(mallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    mallComment selectOneByExample(mallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    mallComment selectOneByExampleSelective(@Param("example") mallCommentExample example, @Param("selective") mallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    List<mallComment> selectByExampleSelective(@Param("example") mallCommentExample example, @Param("selective") mallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    List<mallComment> selectByExample(mallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    mallComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    mallComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    mallComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallComment record, @Param("example") mallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallComment record, @Param("example") mallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}