package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallAftersale;
import org.tiei.mall.db.domain.mallAftersaleExample;

public interface mallAftersaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    long countByExample(mallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int deleteByExample(mallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int insert(mallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int insertSelective(mallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    mallAftersale selectOneByExample(mallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    mallAftersale selectOneByExampleSelective(@Param("example") mallAftersaleExample example, @Param("selective") mallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    List<mallAftersale> selectByExampleSelective(@Param("example") mallAftersaleExample example, @Param("selective") mallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    List<mallAftersale> selectByExample(mallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    mallAftersale selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    mallAftersale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    mallAftersale selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallAftersale record, @Param("example") mallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallAftersale record, @Param("example") mallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}