package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallStorage;
import org.tiei.mall.db.domain.mallStorageExample;

public interface mallStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    long countByExample(mallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    int deleteByExample(mallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    int insert(mallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    int insertSelective(mallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    mallStorage selectOneByExample(mallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    mallStorage selectOneByExampleSelective(@Param("example") mallStorageExample example, @Param("selective") mallStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    List<mallStorage> selectByExampleSelective(@Param("example") mallStorageExample example, @Param("selective") mallStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    List<mallStorage> selectByExample(mallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    mallStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    mallStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    mallStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallStorage record, @Param("example") mallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallStorage record, @Param("example") mallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}