package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallCouponUser;
import org.tiei.mall.db.domain.mallCouponUserExample;

public interface mallCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(mallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(mallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int insert(mallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(mallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    mallCouponUser selectOneByExample(mallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    mallCouponUser selectOneByExampleSelective(@Param("example") mallCouponUserExample example, @Param("selective") mallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    List<mallCouponUser> selectByExampleSelective(@Param("example") mallCouponUserExample example, @Param("selective") mallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    List<mallCouponUser> selectByExample(mallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    mallCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    mallCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    mallCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallCouponUser record, @Param("example") mallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallCouponUser record, @Param("example") mallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}