package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallGoodsSpecification;
import org.tiei.mall.db.domain.mallGoodsSpecificationExample;

public interface mallGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(mallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(mallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    int insert(mallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(mallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    mallGoodsSpecification selectOneByExample(mallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    mallGoodsSpecification selectOneByExampleSelective(@Param("example") mallGoodsSpecificationExample example, @Param("selective") mallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    List<mallGoodsSpecification> selectByExampleSelective(@Param("example") mallGoodsSpecificationExample example, @Param("selective") mallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    List<mallGoodsSpecification> selectByExample(mallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    mallGoodsSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    mallGoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    mallGoodsSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallGoodsSpecification record, @Param("example") mallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallGoodsSpecification record, @Param("example") mallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}