package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallCollect;
import org.tiei.mall.db.domain.mallCollectExample;

public interface mallCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    long countByExample(mallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    int deleteByExample(mallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    int insert(mallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    int insertSelective(mallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    mallCollect selectOneByExample(mallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    mallCollect selectOneByExampleSelective(@Param("example") mallCollectExample example, @Param("selective") mallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    List<mallCollect> selectByExampleSelective(@Param("example") mallCollectExample example, @Param("selective") mallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    List<mallCollect> selectByExample(mallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    mallCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    mallCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    mallCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallCollect record, @Param("example") mallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallCollect record, @Param("example") mallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}