package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallBrand;
import org.tiei.mall.db.domain.mallBrandExample;

public interface mallBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    long countByExample(mallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int deleteByExample(mallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int insert(mallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int insertSelective(mallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    mallBrand selectOneByExample(mallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    mallBrand selectOneByExampleSelective(@Param("example") mallBrandExample example, @Param("selective") mallBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    List<mallBrand> selectByExampleSelective(@Param("example") mallBrandExample example, @Param("selective") mallBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    List<mallBrand> selectByExample(mallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    mallBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    mallBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    mallBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallBrand record, @Param("example") mallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallBrand record, @Param("example") mallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}