package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallRole;
import org.tiei.mall.db.domain.mallRoleExample;

public interface mallRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    long countByExample(mallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int deleteByExample(mallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int insert(mallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int insertSelective(mallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    mallRole selectOneByExample(mallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    mallRole selectOneByExampleSelective(@Param("example") mallRoleExample example, @Param("selective") mallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    List<mallRole> selectByExampleSelective(@Param("example") mallRoleExample example, @Param("selective") mallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    List<mallRole> selectByExample(mallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    mallRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    mallRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    mallRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallRole record, @Param("example") mallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallRole record, @Param("example") mallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}