package org.tiei.mall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tiei.mall.db.domain.mallIssue;
import org.tiei.mall.db.domain.mallIssueExample;

public interface mallIssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    long countByExample(mallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    int deleteByExample(mallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    int insert(mallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    int insertSelective(mallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    mallIssue selectOneByExample(mallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    mallIssue selectOneByExampleSelective(@Param("example") mallIssueExample example, @Param("selective") mallIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    List<mallIssue> selectByExampleSelective(@Param("example") mallIssueExample example, @Param("selective") mallIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    List<mallIssue> selectByExample(mallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    mallIssue selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") mallIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    mallIssue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    mallIssue selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") mallIssue record, @Param("example") mallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") mallIssue record, @Param("example") mallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(mallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(mallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") mallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}